name: GitHub Actions Demo
on: [push]
jobs:
  expore-lerna-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
            node-version: 12

      - run: yarn

      - name: Bootstrap lerna
        run: yarn bootstrap
      
      - name: Bump versions
        run: |
          yarn version:ci:norelease
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
